version: '3'
services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=adminpass
      - MYSQL_PASSWORD=envreq
      - MYSQL_USER=envreq
      - MYSQL_DATABASE=envreqdb
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=envreq
      - DB_PASSWORD=envreq
      - DB_HOST=db
      - DB_PORT=3306
      - DB_INSTANCE=envreqdb
    links:
      - db
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8001:8001"
    links:
      - app
    depends_on:
      - app

volumes:
  mysql_data:
