"""empty message

Revision ID: 1a6220cf3161
Revises: a04ada3ff3d2
Create Date: 2019-03-25 21:38:36.193727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6220cf3161'
down_revision = 'a04ada3ff3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.create_foreign_key(None, 'request', 'environment', ['environment_id'], ['id'])
    op.drop_column('request', 'env_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('env_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.create_foreign_key(None, 'request', 'environment', ['env_id'], ['id'])
    op.drop_column('request', 'environment_id')
    # ### end Alembic commands ###
