"""First migration

Revision ID: a04ada3ff3d2
Revises: 
Create Date: 2019-03-25 18:36:53.342864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04ada3ff3d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developmentphase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ods_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odsnumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odsnumber')
    )
    op.create_table('osb_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osbstack', sa.String(length=20), nullable=True),
    sa.Column('osbstack_ip', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osbstack')
    )
    op.create_table('oss_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ossnumber', sa.Integer(), nullable=True),
    sa.Column('ossworkaccount', sa.String(length=20), nullable=True),
    sa.Column('osshost', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ossnumber')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['developmentphase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('swpnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('env_id', sa.Integer(), nullable=True),
    sa.Column('requestedby', sa.String(length=20), nullable=True),
    sa.Column('approval', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('zones', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('swp_number_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('backup_db', sa.Boolean(), nullable=True),
    sa.Column('keep_data', sa.Boolean(), nullable=True),
    sa.Column('keep_ld', sa.Boolean(), nullable=True),
    sa.Column('osb_id', sa.Integer(), nullable=True),
    sa.Column('ods_id', sa.Integer(), nullable=True),
    sa.Column('oss_id', sa.Integer(), nullable=True),
    sa.Column('source_uat_ref', sa.String(length=10), nullable=True),
    sa.Column('delivery_notification', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['env_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['ods_id'], ['ods_integration.id'], ),
    sa.ForeignKeyConstraint(['osb_id'], ['osb_integration.id'], ),
    sa.ForeignKeyConstraint(['oss_id'], ['oss_integration.id'], ),
    sa.ForeignKeyConstraint(['swp_number_id'], ['swpnumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions_swps',
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('swp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['swp_id'], ['swpnumber.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], )
    )
    op.create_table('envs_requests',
    sa.Column('env_id', sa.Integer(), nullable=True),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['env_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['request.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('envs_requests')
    op.drop_table('versions_swps')
    op.drop_table('request')
    op.drop_table('swpnumber')
    op.drop_table('roles_users')
    op.drop_table('environment')
    op.drop_table('version')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('oss_integration')
    op.drop_table('osb_integration')
    op.drop_table('ods_integration')
    op.drop_table('developmentphase')
    # ### end Alembic commands ###
